server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cities
    username: postgres
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
